#!/bin/bash
wget -O version.txt https://raw.githubusercontent.com/TamaTamaGoGo/MCRPi/release/Update/LatestVersion.txt
MACHINE_TYPE=$(uname -m)
LANG=$(locale language)
ver=$(cat version.txt)

if [ "$LANG" = "ja_JP" ]; then
    echo "日本語に選択されました"
    lang=jp
else
    echo "Automatically selected to English"
    lang=en
    fi

echo "Starting install script"
if [ "$MACHINE_TYPE" = "aarch64" ]; then
    echo "Mode:aarch64 64bit"
    wget https://raw.githubusercontent.com/TamaTamaGoGo/MCRPi---MineCraft-for-RaspberryPi/release/${ver}/${lang}/install64bit
    sudo chmod +x install64bit
    ./install64bit ${lang}
else
    echo "Mode:Not aarch64 32bit"
    wget https://raw.githubusercontent.com/TamaTamaGoGo/MCRPi---MineCraft-for-RaspberryPi/release/${ver}/${lang}/install32bit
    sudo chmod +x install32bit
    ./install32bit ${lang}
    fi
